# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc8250e6f6f86aa2b07cfe3c300e851bdd86006eb34cf44ccc2c72dd66d9c9c9e712b8e962f3c3052b8910b85f9c6aaa0e4eaf10f8a95a9169f02d8c1f24f56a

test:
  secret_key_base: fc1c95f3643b0bb2e7ba46086b2b334f4d452ce78dedaaca84d90ecf6a0470c8f715214f991f8432a130ac28805db7ad2e5fbf176e7b9541230aa8978a03e4e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
